version: "1"

services:
  - type: web
    name: rhodawkai
    env: python
    pythonVersion: 3.11.9
    plan: free
    region: oregon
    repo: https://github.com/Architect8989/RhodawkAI
    rootDir: src/backend
    buildCommand: poetry install
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
